server:
  port: 8080
logging:
  file: target/application.log
spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: ""
        dialect: org.hibernate.dialect.H2Dialect
